# cliff.toml

[changelog]
header = """
# Change Log
"""

body = """
{% for commit in commits %}
    {%- set commit_date = commit.author.timestamp | date(format="%Y-%m-%d") -%}
    {#- æ—¥æœŸåˆ†ç»„é€»è¾‘ -#}
    {%- if loop.first or commit_date != prev_date %}
        {#- å¦‚æœä¸æ˜¯ç¬¬ä¸€æ¡ï¼Œåœ¨æ—¥æœŸå‰æ‰‹åŠ¨æ’å…¥ç©ºè¡Œï¼Œä¿è¯æ®µè½åˆ†éš” -#}
        {%- if not loop.first %}\n{% endif -%}
## {{ commit_date }}
    {% endif -%}
- {{ commit.group }} {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message }}
    {#- è¿™é‡Œçš„ set_global å»æ‰äº†å‰é¢çš„ -ï¼Œç¡®ä¿ä¸Šé¢çš„åˆ—è¡¨é¡¹èƒ½æ­£å¸¸æ¢è¡Œ -#}
    {% set_global prev_date = commit_date %}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
# ä¿æŒæœ€æ–°æ—¥æœŸçš„åœ¨æœ€ä¸Šé¢ï¼ŒåŒä¸€å¤©å†…ä¹Ÿæ˜¯æœ€æ–°çš„åœ¨æœ€ä¸Šé¢
sort_commits = "newest"

commit_parsers = [
    { message = "^(?i)(feat|add)", group = "âœ¨" },
    { message = "^(?i)fix", group = "ğŸ›" },
    { message = "^(?i)docs", group = "ğŸ“" },
    { message = "^(?i)perf", group = "âš¡" },
    { message = "^(?i)refactor", group = "â™»ï¸" },
    { message = "^(?i)style", group = "ğŸ¨" },
    { message = "^(?i)test", group = "ğŸ§ª" },
    { message = "^(?i)chore", skip = true },
    { message = ".*", group = "Other" },
]